<?php

/**
 * Implements hook_theme_suggestions_HOOK() for form suggestion.
 */
function compony_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  $view_id = str_replace('-', '_', $variables['view']->id());
  $view_display = str_replace('-', '_', $variables['view']->current_display);
  $suggestions[] = 'views_view__' . $view_id;
  $suggestions[] = 'views_view__' . $view_id . '__' . $view_display;
}
