component:
  name: 'Field with Full HTML wysiwyg'
  folder_name: field--full-html
  details: 'https://www.compony.io/component/field-full-html'
  downloaded_on: 11-29-2019
  built_upon:
    project: Drupal
    version: '8'
    specific:
      type: core
      link: false
  repository:
    details: 'https://gitlab.com/componies/flat-design/Core/field--full-html'
    gitlab_project_id: '7514156'
    version: 'https://gitlab.com/componies/flat-design/Core/field--full-html/commit/b5baea0fdb64093bdc46e736eaae9114b5ec6e9d'
    version_sha: b5baea0fdb64093bdc46e736eaae9114b5ec6e9d
    version_sha_short: b5baea0f
    diff_with_latest_version: 'https://gitlab.com/componies/flat-design/Core/field--full-html/compare/b5baea0fdb64093bdc46e736eaae9114b5ec6e9d...master'
    clone_this_version: 'git clone https://gitlab.com/componies/flat-design/Core/field--full-html.git field--full-html && cd field--full-html && git checkout b5baea0fdb64093bdc46e736eaae9114b5ec6e9d'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
collection:
  name: 'Bare essentials'
  details: 'https://www.compony.io/collection/bare-essentials'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
supported_by: no-one
