component:
  name: 'Oswald font'
  folder_name: font--oswald
  details: 'https://www.compony.io/component/font-oswald'
  downloaded_on: 11-29-2019
  built_upon:
    project: Drupal
    version: '8'
    specific:
      type: 'custom module'
      link: false
  repository:
    details: 'https://gitlab.com/contributed-components/oswald-font-1053'
    gitlab_project_id: '11257657'
    version: 'https://gitlab.com/contributed-components/oswald-font-1053/commit/d6db938dc5c3d16f751f82f7a7ef7bcc119b309b'
    version_sha: d6db938dc5c3d16f751f82f7a7ef7bcc119b309b
    version_sha_short: d6db938d
    diff_with_latest_version: 'https://gitlab.com/contributed-components/oswald-font-1053/compare/d6db938dc5c3d16f751f82f7a7ef7bcc119b309b...master'
    clone_this_version: 'git clone https://gitlab.com/contributed-components/oswald-font-1053.git font--oswald && cd font--oswald && git checkout d6db938dc5c3d16f751f82f7a7ef7bcc119b309b'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
collection: false
supported_by: no-one
