component:
  name: Pager
  folder_name: pager
  details: 'https://www.compony.io/component/pager'
  downloaded_on: 11-29-2019
  built_upon:
    project: Drupal
    version: '8'
    specific:
      type: core
      link: false
  repository:
    details: 'https://gitlab.com/componies/flat-design/Core/pager'
    gitlab_project_id: '7510279'
    version: 'https://gitlab.com/componies/flat-design/Core/pager/commit/1e331d596f5319afcd866e6f60fdfacacb70c4dc'
    version_sha: 1e331d596f5319afcd866e6f60fdfacacb70c4dc
    version_sha_short: 1e331d59
    diff_with_latest_version: 'https://gitlab.com/componies/flat-design/Core/pager/compare/1e331d596f5319afcd866e6f60fdfacacb70c4dc...master'
    clone_this_version: 'git clone https://gitlab.com/componies/flat-design/Core/pager.git pager && cd pager && git checkout 1e331d596f5319afcd866e6f60fdfacacb70c4dc'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
collection:
  name: 'Bare essentials'
  details: 'https://www.compony.io/collection/bare-essentials'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
supported_by: no-one
