component:
  name: 'Wysiwyg content'
  folder_name: wysiwyg-content
  details: 'https://www.compony.io/component/wysiwyg-content'
  downloaded_on: 11-29-2019
  built_upon:
    project: Drupal
    version: '8'
    specific:
      type: 'custom module'
      link: false
  repository:
    details: 'https://gitlab.com/componies/flat-design/Custom/wysiwyg-content'
    gitlab_project_id: '7522815'
    version: 'https://gitlab.com/componies/flat-design/Custom/wysiwyg-content/commit/5dd0630b45b4157faa722ad2c31ffbc2be5c5d16'
    version_sha: 5dd0630b45b4157faa722ad2c31ffbc2be5c5d16
    version_sha_short: 5dd0630b
    diff_with_latest_version: 'https://gitlab.com/componies/flat-design/Custom/wysiwyg-content/compare/5dd0630b45b4157faa722ad2c31ffbc2be5c5d16...master'
    clone_this_version: 'git clone https://gitlab.com/componies/flat-design/Custom/wysiwyg-content.git wysiwyg-content && cd wysiwyg-content && git checkout 5dd0630b45b4157faa722ad2c31ffbc2be5c5d16'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
collection:
  name: 'Bare essentials'
  details: 'https://www.compony.io/collection/bare-essentials'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
supported_by: no-one
