# Schema for the configuration files of the Bootstrap Barrio Subtheme.

aaweb_subtheme.settings:
  type: theme_settings
  label: 'Bootstrap Barrio Subtheme settings'
  mapping:
    aaweb_sidebar_position:
      type: text
      label: 'Sidebar Position'
    aaweb_content_offset:
      type: integer
      label: 'Offset'
    aaweb_sidebar_first_width:
      type: integer
      label: 'Width'
    aaweb_sidebar_first_offset:
      type: integer
      label: 'Offset'
    aaweb_sidebar_second_width:
      type: integer
      label: 'Width'
    aaweb_sidebar_second_offset:
      type: integer
      label: 'Offset'
    aaweb_footer_layout:
      type: text
      label: 'Layout'
    aaweb_fluid_container:
      type: integer
      label: 'Enabled'
    aaweb_button_size:
      type: text
      label: 'Size'
    aaweb_button_outline:
      type: integer
      label: 'Button outline'
    aaweb_navbar_top_position:
      type: text
      label: 'Position'
    aaweb_navbar_top_color:
      type: integer
      label: 'Color'
    aaweb_navbar_top_background:
      type: text
      label: 'Background'
    aaweb_navbar_position:
      type: text
      label: 'Position'
    aaweb_navbar_color:
      type: integer
      label: 'Color'
    aaweb_navbar_background:
      type: text
      label: 'Background'
    aaweb_anchors_fix:
      type: integer
      label: 'Enabled'
    aaweb_anchors_smooth_scrolling:
      type: integer
      label: 'Enabled'
    aaweb_forms_required_has_error:
      type: integer
      label: 'Enabled'
    aaweb_forms_has_error_value_toggle:
      type: integer
      label: 'Enabled'
    aaweb_forms_smart_descriptions:
      type: integer
      label: 'Enabled'
    aaweb_forms_smart_descriptions_limit:
      type: integer
      label: 'Limit'
    aaweb_forms_smart_descriptions_allowed_tags:
      type: text
      label: 'Allowed tags'
    aaweb_popover_enabled:
      type: integer
      label: 'Enabled'
    aaweb_popover_animation:
      type: integer
      label: 'Enabled'
    aaweb_popover_html:
      type: integer
      label: 'Enabled'
    aaweb_popover_placement:
      type: text
      label: 'Placement'
    aaweb_popover_selector:
      type: text
      label: 'Selector'
    aaweb_popover_trigger_autoclose:
      type: integer
      label: 'Enabled'
    aaweb_popover_delay:
      type: integer
      label: 'Enabled'
    aaweb_popover_trigger:
      type: mapping
      mapping:
        hover:
          type: integer
          label: 'Hover'
    aaweb_tooltip_enabled:
      type: integer
      label: 'Enabled'
    aaweb_tooltip_descriptions:
      type: integer
      label: 'Enabled'
    aaweb_tooltip_descriptions_length:
      type: integer
      label: 'Length'
    aaweb_tooltip_animation:
      type: integer
      label: 'Enabled'
    aaweb_tooltip_html:
      type: integer
      label: 'Length'
    aaweb_tooltip_delay:
      type: integer
      label: 'Enabled'
    aaweb_popover_title:
      type: text
      label: 'Title'
    aaweb_popover_content:
      type: text
      label: 'Content'
    aaweb_tooltip_placement:
      type: text
      label: 'Placement'
    aaweb_tooltip_container:
      type: text
      label: 'Container'
    aaweb_tooltip_selector:
      type: text
      label: 'Selector'
    aaweb_tooltip_trigger:
      type: mapping
      mapping:
        hover:
          type: text
          label: 'Hover'
    aaweb_popover_container:
      type: text
      label: 'Container'