component:
  name: 'Form with basic CSS'
  folder_name: form
  details: 'https://www.compony.io/component/form-with-css'
  downloaded_on: 11-29-2019
  built_upon:
    project: Drupal
    version: '8'
    specific:
      type: core
      link: false
  repository:
    details: 'https://gitlab.com/componies/flat-design/Core/form'
    gitlab_project_id: '7359579'
    version: 'https://gitlab.com/componies/flat-design/Core/form/commit/c2958bd74eaf7755d13efaee3ce35e7f9a76277e'
    version_sha: c2958bd74eaf7755d13efaee3ce35e7f9a76277e
    version_sha_short: c2958bd7
    diff_with_latest_version: 'https://gitlab.com/componies/flat-design/Core/form/compare/c2958bd74eaf7755d13efaee3ce35e7f9a76277e...master'
    clone_this_version: 'git clone https://gitlab.com/componies/flat-design/Core/form.git form && cd form && git checkout c2958bd74eaf7755d13efaee3ce35e7f9a76277e'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
collection:
  name: 'Bare essentials'
  details: 'https://www.compony.io/collection/bare-essentials'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
supported_by: no-one
