component:
  name: 'Status messages'
  folder_name: status-messages
  details: 'https://www.compony.io/component/status-messages'
  downloaded_on: 11-29-2019
  built_upon:
    project: Drupal
    version: '8'
    specific:
      type: core
      link: false
  repository:
    details: 'https://gitlab.com/componies/flat-design/Core/status-messages'
    gitlab_project_id: '7511021'
    version: 'https://gitlab.com/componies/flat-design/Core/status-messages/commit/a3c2d4f2d25876d4e3272c2f4ec47d0628ea01c1'
    version_sha: a3c2d4f2d25876d4e3272c2f4ec47d0628ea01c1
    version_sha_short: a3c2d4f2
    diff_with_latest_version: 'https://gitlab.com/componies/flat-design/Core/status-messages/compare/a3c2d4f2d25876d4e3272c2f4ec47d0628ea01c1...master'
    clone_this_version: 'git clone https://gitlab.com/componies/flat-design/Core/status-messages.git status-messages && cd status-messages && git checkout a3c2d4f2d25876d4e3272c2f4ec47d0628ea01c1'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
collection:
  name: 'Bare essentials'
  details: 'https://www.compony.io/collection/bare-essentials'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
supported_by: no-one
