component:
  name: Page
  folder_name: page
  details: 'https://www.compony.io/component/page'
  downloaded_on: 11-29-2019
  built_upon:
    project: Drupal
    version: '8'
    specific:
      type: core
      link: false
  repository:
    details: 'https://gitlab.com/componies/flat-design/Core/page'
    gitlab_project_id: '7315009'
    version: 'https://gitlab.com/componies/flat-design/Core/page/commit/74096f1323ac15b64bbcab68952eca63e8e3b90a'
    version_sha: 74096f1323ac15b64bbcab68952eca63e8e3b90a
    version_sha_short: 74096f13
    diff_with_latest_version: 'https://gitlab.com/componies/flat-design/Core/page/compare/74096f1323ac15b64bbcab68952eca63e8e3b90a...master'
    clone_this_version: 'git clone https://gitlab.com/componies/flat-design/Core/page.git page && cd page && git checkout 74096f1323ac15b64bbcab68952eca63e8e3b90a'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
collection:
  name: 'Bare essentials'
  details: 'https://www.compony.io/collection/bare-essentials'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
supported_by: no-one
