component:
  name: 'Unformatted views view'
  folder_name: views-view-unformatted
  details: 'https://www.compony.io/component/views-view-unformatted'
  downloaded_on: 11-29-2019
  built_upon:
    project: Drupal
    version: '8'
    specific:
      type: core
      link: false
  repository:
    details: 'https://gitlab.com/componies/flat-design/Core/views-view-unformatted'
    gitlab_project_id: '8073125'
    version: 'https://gitlab.com/componies/flat-design/Core/views-view-unformatted/commit/71d2a6184f59afbf141c617efd9b4c55dbdef6f3'
    version_sha: 71d2a6184f59afbf141c617efd9b4c55dbdef6f3
    version_sha_short: 71d2a618
    diff_with_latest_version: 'https://gitlab.com/componies/flat-design/Core/views-view-unformatted/compare/71d2a6184f59afbf141c617efd9b4c55dbdef6f3...master'
    clone_this_version: 'git clone https://gitlab.com/componies/flat-design/Core/views-view-unformatted.git views-view-unformatted && cd views-view-unformatted && git checkout 71d2a6184f59afbf141c617efd9b4c55dbdef6f3'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
collection:
  name: 'Bare essentials'
  details: 'https://www.compony.io/collection/bare-essentials'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
supported_by: no-one
