component:
  name: 'Field with basic HTML wysiwyg'
  folder_name: field--basic-html
  details: 'https://www.compony.io/component/field-basic-html'
  downloaded_on: 11-29-2019
  built_upon:
    project: Drupal
    version: '8'
    specific:
      type: core
      link: false
  repository:
    details: 'https://gitlab.com/componies/flat-design/Core/field--basic-html'
    gitlab_project_id: '7514160'
    version: 'https://gitlab.com/componies/flat-design/Core/field--basic-html/commit/5f8d092d52c617d1436e3ced5cab69836b55cc93'
    version_sha: 5f8d092d52c617d1436e3ced5cab69836b55cc93
    version_sha_short: 5f8d092d
    diff_with_latest_version: 'https://gitlab.com/componies/flat-design/Core/field--basic-html/compare/5f8d092d52c617d1436e3ced5cab69836b55cc93...master'
    clone_this_version: 'git clone https://gitlab.com/componies/flat-design/Core/field--basic-html.git field--basic-html && cd field--basic-html && git checkout 5f8d092d52c617d1436e3ced5cab69836b55cc93'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
collection:
  name: 'Bare essentials'
  details: 'https://www.compony.io/collection/bare-essentials'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
supported_by: no-one
