component:
  name: Field
  folder_name: field
  details: 'https://www.compony.io/component/field'
  downloaded_on: 11-29-2019
  built_upon:
    project: Drupal
    version: '8'
    specific:
      type: core
      link: false
  repository:
    details: 'https://gitlab.com/componies/flat-design/Core/field'
    gitlab_project_id: '7514073'
    version: 'https://gitlab.com/componies/flat-design/Core/field/commit/65877f55b9c0a35a425a4fee863e678d7448ca89'
    version_sha: 65877f55b9c0a35a425a4fee863e678d7448ca89
    version_sha_short: 65877f55
    diff_with_latest_version: 'https://gitlab.com/componies/flat-design/Core/field/compare/65877f55b9c0a35a425a4fee863e678d7448ca89...master'
    clone_this_version: 'git clone https://gitlab.com/componies/flat-design/Core/field.git field && cd field && git checkout 65877f55b9c0a35a425a4fee863e678d7448ca89'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
collection:
  name: 'Bare essentials'
  details: 'https://www.compony.io/collection/bare-essentials'
  contributors:
    1:
      name: Compony
      details: 'https://www.compony.io/user/1'
supported_by: no-one
